---

data_dir: /hdd/malay/autistic_behavior_recognition/
preproc_data_dir: /hdd/malay/autistic_behavior_recognition/preprocessed/
model_dir: /hdd/malay/models/
yolo_conf: yolov5lu.pt
csv_fp: ASBD.csv
clip_len: 30
batch_size: 4
lr: 0.0001
num_epochs: 10
#model: VST
model: VSTWithCLIP
# setting: binary
setting: multiclass
categories: [
    normal,
    walkingaway,
    throwing,
    selfhitting,
    selfbiting,
    screaming,
    running,
    rolling,
    pullinghair,
    jumping,
    hittingothers,
    headbanging,
    crying,
    handaction,
    armflapping,
    spinning
]